### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by RaphaelMayr** [br-automation-com/PahoMQTT_Library#3]
@patricthysell 
Hello, there,

I'm relatively new to AS, but I wanted to try this MQTT example. 

First of all, what's my problem?
![error](https://user-images.githubusercontent.com/23212379/48617101-c5a31b80-e995-11e8-8a8f-af43bb30272e.png)

When I compile the project, it runs smoothly and generates the executable code. But when I flash this code into the B&R controller, the problem comes, as seen above, that the controller doesn't find the library and then writes "ARES?". But this error refers to "inet_aton" which isn't used in the basic program, or have I overlooked it? The controller then starts several times and is only accessible in diagnostic mode.

What I have done so far:

- Setting up a simple project
- The library PahoMQTT (version v4.26.0-rev.10 and v4.34.0-rev.10 both tried) added
- Adding the Library in the Runtime
- That's it, just transferred and then the error occurs.

Did I miss something? Or what am I doing wrong? Without the library the project will be transferred without problems. 

Some additional information: 
AS version 4.4.5.61, with a student license, 
The controller I've used is the X20CP1584 and a 5PC900_TS17_00, but the error occurs with both
Automation Runtime A4.45 and F4.44 
GCC Compiler version V4.1.2

Thanks already once for the help.

Yours sincerely

**Comment by patricthysell** [comment]
Hi @RaphaelMayr 
Your problem is that you are using the wrong Automation Runtime (AR) version.
The Paho Library is compiled for versions 4,26 and 4.34
As a little background information:
Automation Runtime versions have different revisions, starting from A and ending up in V when no more  revisions are made for this certain version, For example, I have tested Paho V4.34-rev10 with Automation Runtime E4.34, but it also works with Automation Runtime I4.34. However, it does NOT work with AR A4.45 or AR F4.44, as these are not binary comatible with the runtime I used for building PahoMQTT.

I tried to mention this relation in the README, But I will check if I can output a runtime error in the library if the Paho runs with an incomatible runtime, as you are not the first one to ask.

So get a Automation Runtime 4.34, or wait for a Paho V4.44 or Paho 4.45 
cheers

**Comment by RaphaelMayr** [comment]
Hello @patricthysell,
thanks for your quick responce. I changed the Automation Runtime to E4.34 and it perfectly worked.

However, I wanted to ask if it is likely that you will update the PahoMQTT to the latest version (A4.45), because I would like to use the library on the APC910 with hypervisor, which unfortunately does not work with the AR E4.34. If so, can we expect this update this year or early next year or will it take longer? 

Thank you in advance.

**Comment by patricthysell** [comment]
@RaphaelMayr, Yes, I will have a new version - probably within November - using B4.45

**Comment by Namdevrj** [comment]
Hi,
I am working on automation studio 4.6 and integrated MQTT library V4.45.0-rev.11. Compilation is successful as shown in the attached image, but i am not able to see data on MQTT broker currently we configured mosquitto as MQTT broker.
Data transfer is not happening using MQTT sample application, whether any setting is required other than steps mentioned in the link: https://github.com/br-automation-com/PahoMQTT_Library/blob/master/README.md

![Capture](https://user-images.githubusercontent.com/59044715/71152461-7eecb880-225c-11ea-850f-858bfc97dc41.PNG)
